#!/usr/bin/env python3
# gen_comb_table.py - signed fixed-base comb table generator for Ed25519.
#   Generalized to arbitrary number of teeth t.
#
#   Convention (matches meshchat64 COMB_LOADPT_S / CB_RECODE):
#     L  = t * W   bits covered (W = ceil(258/t)); recode forces bit L-1.
#     TABLE[idx] = sum_{i=0}^{t-1} sigma_i * 2^(i*W) * B   (idx in 0..2^(t-1)-1)
#       sigma_0 = +1 (always)
#       sigma_i = +1 if bit(i-1) of idx == 0, else -1     (i = 1..t-1)
#     Each point stored affine little-endian: X[32] then Y[32] = 64 bytes.
#
#   The per-step point the comb loop adds is sum_i (2*b_i - 1)*2^(i*W)*B,
#   which equals +/-TABLE[idx] after the CB_NEG (tooth0) negation. Proven
#   identity: recode u'=m (m odd, m<2^(L-1)) => u'*B = m*B.
#
#   t=6  -> 32 points,   2 KB  (in C64 RAM, current production)
#   t=12 -> 2048 points, 128 KB (REU)
#   t=16 -> 32768 points, 2 MB  (REU)

import sys, os, math
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ref_ed import p, B, scalar_mul, to_affine

ORDER = 2**252 + 27742317777372353535851937790883648493

def comb_W(t):
    return math.ceil(258 / t)

def point_bytes(n):
    """affine (x,y) of n*B, little-endian 32+32 bytes."""
    x, y = to_affine(scalar_mul(n % ORDER, B))
    return x.to_bytes(32, "little") + y.to_bytes(32, "little")

def table_point_index(idx, t, W):
    """integer scalar n such that n*B = TABLE[idx]."""
    n = 1  # sigma_0 = +1, tooth 0
    for i in range(1, t):
        sgn = -1 if (idx >> (i - 1)) & 1 else 1
        n += sgn * (1 << (i * W))
    return n

def gen_table(t):
    W = comb_W(t)
    npts = 1 << (t - 1)
    out = bytearray()
    for idx in range(npts):
        n = table_point_index(idx, t, W)
        out += point_bytes(n)
    return bytes(out), W, npts

def emit_inc(t, addr=None):
    data, W, npts = gen_table(t)
    lines = []
    lines.append(f"; comb_table.inc (generated by gen_comb_table.py) - {npts} x 64 bytes (X,Y affine LE)")
    lines.append(f"; signed-comb h={t}: TABLE[idx] = sum_i sigma_i*2^(iW)*B ; sigma_0=+1")
    if addr is not None:
        lines.append(f"* = ${addr:04X}")
    lines.append("COMB_TABLE")
    for pi in range(npts):
        lines.append(f"  ; punt {pi}")
        pt = data[pi*64:(pi+1)*64]
        for row in range(4):
            chunk = pt[row*16:(row+1)*16]
            lines.append("  !byte " + ",".join(f"${b:02x}" for b in chunk))
    return "\n".join(lines) + "\n", data

def emit_bin(t):
    data, W, npts = gen_table(t)
    return data, W, npts

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("-t", type=int, default=6, help="number of teeth")
    ap.add_argument("--addr", default="A900", help="C64 load addr (hex) for .inc, '' to omit")
    ap.add_argument("--inc", help="write ACME .inc to this path")
    ap.add_argument("--bin", help="write raw table bytes to this path")
    args = ap.parse_args()
    addr = int(args.addr, 16) if args.addr else None
    W = comb_W(args.t)
    print(f"t={args.t}  W={W}  doublings={W}  points={1<<(args.t-1)}  size={(1<<(args.t-1))*64} B")
    if args.inc:
        text, _ = emit_inc(args.t, addr)
        open(args.inc, "w").write(text)
        print("wrote", args.inc)
    if args.bin:
        data, _, _ = emit_bin(args.t)
        open(args.bin, "wb").write(data)
        print("wrote", args.bin, len(data), "bytes")
